const constantNotify = {
    ACCESS_TOKEN: 'optech12345!@#',
    REFRESH_TOKEN: 'optech123456!@#',
    TOKEN_TIME_LIFE: '7d',
    REFRESH_TOKEN_TIME_LIFE: '7d',
    DEFAULT_LIMIT: '',
    VALIDATE_BODY: 'không được để trống',
    ADD_DATA_SUCCESS: 'Thêm thành công',
    ADD_DATA_FAILED: 'Thêm thất bại',
    ACCOUNT_FAILED: 'Tài khoản không chính xác',
    PASS_FAILED: 'Mật khẩu không chính xác',
    EMAIL_FAILED: 'Email không chính xác',
    PASS_OLD_FAILED: 'Mật khẩu cũ không chính xác',
    UPDATE_DATA_SUCCESS: 'Cập nhật thành công',
    CONNECT_SUCCESS: 'Kết nối thành công',
    UPDATE_DATA_FAILED: 'Cập nhật thất bại',
    DELETE_DATA_SUCCESS: 'Xóa thành công',
    ERROR: 'Đã xãy ra lỗi',
    ERROR_SERI: 'Seri thuê bao đã bị lỗi',
    EXPIRED_ON_SOTHUEBAO: 'Số thuê bao đã hết hạn',
    EXPIRED_ON_PASS: 'Mật khẩu do hệ thống cấp đã hết hạn',
    ALREADY_EXITS_SERI: 'Seri thuê bao đã tồn tại',
    ALREADY_EXITS_SOTHUEBAO: 'Số thuê bao đã tồn tại',
    ALREADY_EXITS: 'đã tồn tại',
    NOT_ACTIVE_ACCOUNT: 'Tài khoản chưa được kích hoạt',
    NOT_EXITS: 'không tồn tại',
    NOT_EXITS_IMEI: 'IMEI thiết bị không tồn tại',
    NOT_EXITS_SERI: 'Seri thuê bao không tồn tại',
    NOT_EXITS_SOTHUEBAO: 'Số thuê bao không tồn tại',
    OBTAIN: 'Đã bán',
    NOT_OBTAIN: 'Chưa bán',
    COMPLETE: 'Đã thanh toán',
    NOT_COMPLETE: 'Chưa thanh toán',
    USED_IMEI: 'IMEI thiết bị đã được sử dụng',
    USED_NAME: 'Tên thiết bị đã được sử dụng',
    USED_SERI: 'Seri thuê bao đã được sử dụng',
    USED_SOTHUEBAO: 'Số thuê bao đã được sử dụng',
    NOT_USE_SOTHUEBAO: 'Số thuê bao chưa được sử dụng',
    IS_NUMBER: 'Dữ liệu bắt buộc là số',
    IS_EMAIL: 'Trường này là email',
    DATALESS1000: 'Dữ liệu phải nhỏ hơn 1000 dòng',
    MOVE_SOTHUEBAO_SUCCESS: 'Chuyển số thuê bao thành công',
    VALIDATE_ACCOUNT: 'Tài khoản chỉ chứa kí tự thường và số',
    VALIDATE_PASS: 'Mật khẩu bao gồm ít nhất 1 kí tự in hoa, chữ, số và không chứa kí tự đặc biệt',
    CHECK_EMAIL: 'Vui lòng kiểm tra email để nhận lại mật khẩu!',
    CHANGE_PASS_SUCCESS: 'Thay đổi mật khẩu thành công',
};

module.exports = constantNotify;
